-- Auto-generated by Matugen

require('base16-colorscheme').setup({
    base00 = '#091517',
    base01 = '#041012',
    base02 = '#111e1f',
    base03 = '#324b4e',
    base04 = '#b1cbcf',
    base05 = '#d7e5e7',
    base06 = '#263334',
    base07 = '#2f3b3d',

    base08 = '#ffb4ab',
    base09 = '#81d3dd',
    base0A = '#96d5a6',
    base0B = '#7eda9a',
    base0C = '#004f55',
    base0D = '#00522a',
    base0E = '#13512d',
    base0F = '#b2f1c0',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
    for _, v in pairs(groups) do
        vim.api.nvim_set_hl(0, v, value)
    end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
    bg = '#00522a',
    fg = '#091517',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
    fg = '#9df0f9',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
    fg = '#81d3dd',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
    fg = '#96d5a6',
})

vim.api.nvim_set_hl(0, 'Keyword', {
    fg = '#006d3a',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
    bg = '#041012',
    fg = '#7eda9a',
})
