-- require 'soil'.setup {
--     -- If you want to use Plant UML jar version instead of the install version
--     -- puml_jar = "/path/to/plantuml.jar",
--
--     -- If you want to customize the image showed when running this plugin
--     image = {
--         darkmode = false, -- Enable or disable darkmode
--         format = "svg",   -- Choose between png or svg
--
--         -- This is a default implementation of using nsxiv to open the resultant image
--         -- Edit the string to use your preferred app to open the image (as if it were a command line)
--         -- Some examples:
--         -- return "feh " .. img
--         -- return "xdg-open " .. img
--         execute_to_open = function(img)
--             -- return ":! feh '" .. img .. "'"
--             vim.cmd("silent :! feh '" .. img .. "' &")
--             return ""
--         end
--     }
-- }



-- vim.api.nvim_create_autocmd("BufWritePost", {
--     pattern = "*.puml",
--     -- callback = compile_and_open_pdf(),
--     callback = function()
--         vim.cmd(":Soil")
--     end,
-- })
